apiVersion: v1
kind: Service
metadata:
  name: graphqlegitim-srv
spec:
  type: NodePort
  selector:
    app: graphqlegitim
  ports:
    - name: graphqlegitim
      protocol: TCP
      port: 8080
      targetPort: 8080